# Generated by Django 3.0.5 on 2020-05-03 08:47
# -*- coding: utf-8 -*-

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('allergens', models.TextField(default=None)),
                ('nutriscore', models.CharField(max_length=1)),
                ('store', models.CharField(max_length=50)),
                ('picture', models.URLField()),
                ('url_OpenFF', models.URLField()),
                ('linked_cat', models.ManyToManyField(to='purbeurre.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_search', models.DateTimeField(auto_now_add=True)),
                ('fk_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.Account')),
                ('fk_food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='purbeurre.FoodItem')),
                ('fk_substitute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='purbeurre.FoodItem')),
            ],
        ),
    ]
