# Generated by Django 3.0.5 on 2020-05-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='store',
            field=models.CharField(max_length=100),
        ),
    ]
